// <auto-generated/>
using Chat.Client.Models;
using Chat.Client.Repositories.Contract;
using D20Tek.Blazor.BrowserStorage;
using Microsoft.AspNetCore.Components;
using System.Net;

namespace Chat.Client.Pages;

public class LoginBase : ComponentBase
{
    [Inject]
    IUserIntegration userIntegration { get; set; }
    [Inject]
    NavigationManager navigationManager { get; set; }
    [Inject]
    ILocalStorageService localStorageService { get; set; }

    protected LoginModel _model = new();
    protected string Token { get; set; }

    protected async Task LoginClicked()
    {
        var (statusCode, response) = await userIntegration.Login(_model);


        bool isOk = statusCode == HttpStatusCode.OK;
        bool isBadRequest = statusCode == HttpStatusCode.BadRequest;

        if (isOk)
        {
            await localStorageService.SetAsync("token", response);
            navigationManager.NavigateTo($"/login-successfully/{response}");
        }
        else if (isBadRequest) navigationManager.NavigateTo($"/error/{response}");

    }

}
