// <auto-generated/>
using Chat.Client.Models;
using Chat.Client.Repositories.Contract;
using Microsoft.AspNetCore.Components;
using System.Net;

namespace Chat.Client.Pages;

public class LoginBase : ComponentBase
{
    [Inject]
    IUserIntegration userIntegration { get; set; }
    [Inject]
    NavigationManager navigationManager { get; set; }   

    protected LoginModel _model = new();
    protected string Token { get; set; }

    protected async Task LoginClicked()
    {
        var (statusCode, response) = await userIntegration.Login(_model);


        bool isOk = statusCode == HttpStatusCode.OK;
        bool isBadRequest = statusCode == HttpStatusCode.BadRequest;

        if (isOk) navigationManager.NavigateTo($"/login-successfully/{response}");
        else if (isBadRequest) navigationManager.NavigateTo($"/error/{response}");

    }

}
