// <auto-generated/>
using Chat.Client.Models;
using Chat.Client.Repositories.Contract;
using Microsoft.AspNetCore.Components;
using System.Net;

namespace Chat.Client.Pages;

public class LoginBase(
    IUserIntegration userIntegration,
    NavigationManager navigationManager) : ComponentBase
{
    protected LoginModel _model = new();
    protected string Token { get; set; }

    private async Task LoginClicked()
    {
        var (statusCode, response) = await userIntegration.Login(_model);


        bool isOk = statusCode == HttpStatusCode.OK;
        bool isBadRequest = statusCode == HttpStatusCode.BadRequest;

        if (isOk) navigationManager.NavigateTo($"/login-successfully/{response}");
        else if (isBadRequest) navigationManager.NavigateTo($"/error/{response}");

    }

}
